rips_distance_matrix_persistence.exe -o kyberS10Step2.txt -r 6 -d 4 -p 2 ./RW2/kyberS10Step2.csv
rips_distance_matrix_persistence.exe -o kyberS10Step3.txt -r 6 -d 4 -p 2 ./RW2/kyberS10Step3.csv
rips_distance_matrix_persistence.exe -o kyberS10Step4.txt -r 6 -d 4 -p 2 ./RW2/kyberS10Step4.csv
rips_distance_matrix_persistence.exe -o kyberS10Step5.txt -r 6 -d 4 -p 2 ./RW2/kyberS10Step5.csv
rips_distance_matrix_persistence.exe -o kyberS11Step2.txt -r 6 -d 4 -p 2 ./RW2/kyberS11Step2.csv
rips_distance_matrix_persistence.exe -o kyberS11Step3.txt -r 6 -d 4 -p 2 ./RW2/kyberS11Step3.csv
rips_distance_matrix_persistence.exe -o kyberS11Step4.txt -r 6 -d 4 -p 2 ./RW2/kyberS11Step4.csv
rips_distance_matrix_persistence.exe -o kyberS11Step5.txt -r 6 -d 4 -p 2 ./RW2/kyberS11Step5.csv
rips_distance_matrix_persistence.exe -o kyberS12Step2.txt -r 6 -d 4 -p 2 ./RW2/kyberS12Step2.csv
rips_distance_matrix_persistence.exe -o kyberS12Step3.txt -r 6 -d 4 -p 2 ./RW2/kyberS12Step3.csv
rips_distance_matrix_persistence.exe -o kyberS12Step4.txt -r 6 -d 4 -p 2 ./RW2/kyberS12Step4.csv
rips_distance_matrix_persistence.exe -o kyberS12Step5.txt -r 6 -d 4 -p 2 ./RW2/kyberS12Step5.csv
rips_distance_matrix_persistence.exe -o kyberS13Step2.txt -r 6 -d 4 -p 2 ./RW2/kyberS13Step2.csv
rips_distance_matrix_persistence.exe -o kyberS13Step3.txt -r 6 -d 4 -p 2 ./RW2/kyberS13Step3.csv
rips_distance_matrix_persistence.exe -o kyberS13Step4.txt -r 6 -d 4 -p 2 ./RW2/kyberS13Step4.csv
rips_distance_matrix_persistence.exe -o kyberS13Step5.txt -r 6 -d 4 -p 2 ./RW2/kyberS13Step5.csv
rips_distance_matrix_persistence.exe -o kyberS14Step2.txt -r 6 -d 4 -p 2 ./RW2/kyberS14Step2.csv
rips_distance_matrix_persistence.exe -o kyberS14Step3.txt -r 6 -d 4 -p 2 ./RW2/kyberS14Step3.csv
rips_distance_matrix_persistence.exe -o kyberS14Step4.txt -r 6 -d 4 -p 2 ./RW2/kyberS14Step4.csv
rips_distance_matrix_persistence.exe -o kyberS14Step5.txt -r 6 -d 4 -p 2 ./RW2/kyberS14Step5.csv
rips_distance_matrix_persistence.exe -o kyberS15Step2.txt -r 6 -d 4 -p 2 ./RW2/kyberS15Step2.csv
rips_distance_matrix_persistence.exe -o kyberS15Step3.txt -r 6 -d 4 -p 2 ./RW2/kyberS15Step3.csv
rips_distance_matrix_persistence.exe -o kyberS15Step4.txt -r 6 -d 4 -p 2 ./RW2/kyberS15Step4.csv
rips_distance_matrix_persistence.exe -o kyberS15Step5.txt -r 6 -d 4 -p 2 ./RW2/kyberS15Step5.csv
rips_distance_matrix_persistence.exe -o kyberS16Step2.txt -r 6 -d 4 -p 2 ./RW2/kyberS16Step2.csv
rips_distance_matrix_persistence.exe -o kyberS16Step3.txt -r 6 -d 4 -p 2 ./RW2/kyberS16Step3.csv
rips_distance_matrix_persistence.exe -o kyberS16Step4.txt -r 6 -d 4 -p 2 ./RW2/kyberS16Step4.csv
rips_distance_matrix_persistence.exe -o kyberS16Step5.txt -r 6 -d 4 -p 2 ./RW2/kyberS16Step5.csv
rips_distance_matrix_persistence.exe -o kyberS17Step2.txt -r 6 -d 4 -p 2 ./RW2/kyberS17Step2.csv
rips_distance_matrix_persistence.exe -o kyberS17Step3.txt -r 6 -d 4 -p 2 ./RW2/kyberS17Step3.csv
rips_distance_matrix_persistence.exe -o kyberS17Step4.txt -r 6 -d 4 -p 2 ./RW2/kyberS17Step4.csv
rips_distance_matrix_persistence.exe -o kyberS17Step5.txt -r 6 -d 4 -p 2 ./RW2/kyberS17Step5.csv
rips_distance_matrix_persistence.exe -o kyberS18Step2.txt -r 6 -d 4 -p 2 ./RW2/kyberS18Step2.csv
rips_distance_matrix_persistence.exe -o kyberS18Step3.txt -r 6 -d 4 -p 2 ./RW2/kyberS18Step3.csv
rips_distance_matrix_persistence.exe -o kyberS18Step4.txt -r 6 -d 4 -p 2 ./RW2/kyberS18Step4.csv
rips_distance_matrix_persistence.exe -o kyberS18Step5.txt -r 6 -d 4 -p 2 ./RW2/kyberS18Step5.csv
rips_distance_matrix_persistence.exe -o kyberS19Step2.txt -r 6 -d 4 -p 2 ./RW2/kyberS19Step2.csv
rips_distance_matrix_persistence.exe -o kyberS19Step3.txt -r 6 -d 4 -p 2 ./RW2/kyberS19Step3.csv
rips_distance_matrix_persistence.exe -o kyberS19Step4.txt -r 6 -d 4 -p 2 ./RW2/kyberS19Step4.csv
rips_distance_matrix_persistence.exe -o kyberS19Step5.txt -r 6 -d 4 -p 2 ./RW2/kyberS19Step5.csv
rips_distance_matrix_persistence.exe -o kyberS1Step2.txt -r 6 -d 4 -p 2 ./RW2/kyberS1Step2.csv
rips_distance_matrix_persistence.exe -o kyberS1Step3.txt -r 6 -d 4 -p 2 ./RW2/kyberS1Step3.csv
rips_distance_matrix_persistence.exe -o kyberS1Step4.txt -r 6 -d 4 -p 2 ./RW2/kyberS1Step4.csv
rips_distance_matrix_persistence.exe -o kyberS1Step5.txt -r 6 -d 4 -p 2 ./RW2/kyberS1Step5.csv
rips_distance_matrix_persistence.exe -o kyberS20Step2.txt -r 6 -d 4 -p 2 ./RW2/kyberS20Step2.csv
rips_distance_matrix_persistence.exe -o kyberS20Step3.txt -r 6 -d 4 -p 2 ./RW2/kyberS20Step3.csv
rips_distance_matrix_persistence.exe -o kyberS20Step4.txt -r 6 -d 4 -p 2 ./RW2/kyberS20Step4.csv
rips_distance_matrix_persistence.exe -o kyberS20Step5.txt -r 6 -d 4 -p 2 ./RW2/kyberS20Step5.csv
rips_distance_matrix_persistence.exe -o kyberS2Step2.txt -r 6 -d 4 -p 2 ./RW2/kyberS2Step2.csv
rips_distance_matrix_persistence.exe -o kyberS2Step3.txt -r 6 -d 4 -p 2 ./RW2/kyberS2Step3.csv
rips_distance_matrix_persistence.exe -o kyberS2Step4.txt -r 6 -d 4 -p 2 ./RW2/kyberS2Step4.csv
rips_distance_matrix_persistence.exe -o kyberS2Step5.txt -r 6 -d 4 -p 2 ./RW2/kyberS2Step5.csv
rips_distance_matrix_persistence.exe -o kyberS3Step2.txt -r 6 -d 4 -p 2 ./RW2/kyberS3Step2.csv
rips_distance_matrix_persistence.exe -o kyberS3Step3.txt -r 6 -d 4 -p 2 ./RW2/kyberS3Step3.csv
rips_distance_matrix_persistence.exe -o kyberS3Step4.txt -r 6 -d 4 -p 2 ./RW2/kyberS3Step4.csv
rips_distance_matrix_persistence.exe -o kyberS3Step5.txt -r 6 -d 4 -p 2 ./RW2/kyberS3Step5.csv
rips_distance_matrix_persistence.exe -o kyberS4Step2.txt -r 6 -d 4 -p 2 ./RW2/kyberS4Step2.csv
rips_distance_matrix_persistence.exe -o kyberS4Step3.txt -r 6 -d 4 -p 2 ./RW2/kyberS4Step3.csv
rips_distance_matrix_persistence.exe -o kyberS4Step4.txt -r 6 -d 4 -p 2 ./RW2/kyberS4Step4.csv
rips_distance_matrix_persistence.exe -o kyberS4Step5.txt -r 6 -d 4 -p 2 ./RW2/kyberS4Step5.csv
rips_distance_matrix_persistence.exe -o kyberS5Step2.txt -r 6 -d 4 -p 2 ./RW2/kyberS5Step2.csv
rips_distance_matrix_persistence.exe -o kyberS5Step3.txt -r 6 -d 4 -p 2 ./RW2/kyberS5Step3.csv
rips_distance_matrix_persistence.exe -o kyberS5Step4.txt -r 6 -d 4 -p 2 ./RW2/kyberS5Step4.csv
rips_distance_matrix_persistence.exe -o kyberS5Step5.txt -r 6 -d 4 -p 2 ./RW2/kyberS5Step5.csv
rips_distance_matrix_persistence.exe -o kyberS6Step2.txt -r 6 -d 4 -p 2 ./RW2/kyberS6Step2.csv
rips_distance_matrix_persistence.exe -o kyberS6Step3.txt -r 6 -d 4 -p 2 ./RW2/kyberS6Step3.csv
rips_distance_matrix_persistence.exe -o kyberS6Step4.txt -r 6 -d 4 -p 2 ./RW2/kyberS6Step4.csv
rips_distance_matrix_persistence.exe -o kyberS6Step5.txt -r 6 -d 4 -p 2 ./RW2/kyberS6Step5.csv
rips_distance_matrix_persistence.exe -o kyberS7Step2.txt -r 6 -d 4 -p 2 ./RW2/kyberS7Step2.csv
rips_distance_matrix_persistence.exe -o kyberS7Step3.txt -r 6 -d 4 -p 2 ./RW2/kyberS7Step3.csv
rips_distance_matrix_persistence.exe -o kyberS7Step4.txt -r 6 -d 4 -p 2 ./RW2/kyberS7Step4.csv
rips_distance_matrix_persistence.exe -o kyberS7Step5.txt -r 6 -d 4 -p 2 ./RW2/kyberS7Step5.csv
rips_distance_matrix_persistence.exe -o kyberS8Step2.txt -r 6 -d 4 -p 2 ./RW2/kyberS8Step2.csv
rips_distance_matrix_persistence.exe -o kyberS8Step3.txt -r 6 -d 4 -p 2 ./RW2/kyberS8Step3.csv
rips_distance_matrix_persistence.exe -o kyberS8Step4.txt -r 6 -d 4 -p 2 ./RW2/kyberS8Step4.csv
rips_distance_matrix_persistence.exe -o kyberS8Step5.txt -r 6 -d 4 -p 2 ./RW2/kyberS8Step5.csv
rips_distance_matrix_persistence.exe -o kyberS9Step2.txt -r 6 -d 4 -p 2 ./RW2/kyberS9Step2.csv
rips_distance_matrix_persistence.exe -o kyberS9Step3.txt -r 6 -d 4 -p 2 ./RW2/kyberS9Step3.csv
rips_distance_matrix_persistence.exe -o kyberS9Step4.txt -r 6 -d 4 -p 2 ./RW2/kyberS9Step4.csv
rips_distance_matrix_persistence.exe -o kyberS9Step5.txt -r 6 -d 4 -p 2 ./RW2/kyberS9Step5.csv
